apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.albHealthCheckPath }}
{{- if .Values.appJava }}
    alb.ingress.kubernetes.io/healthcheck-port: 'monitoring'
{{- end }}
spec:
  ports:
  - name: application
    port: 80
{{- if .Values.customNodePort }}
    nodePort: {{ .Values.customNodePort }}
{{- end }}
    targetPort: application
    protocol: TCP
{{- if .Values.appJava }}
  - name: monitoring
    port: 4444
{{- if .Values.customNodePortHealthCheck }}
    nodePort: {{ .Values.customNodePortHealthCheck }}
{{- end }}
    targetPort: monitoring
    protocol: TCP
{{- end }}
  selector:
    app: {{ .Release.Name }}
  type: NodePort
